### ISSUE TITLE
does not compile

### ISSUE THREAD

**Issue by BlockchainPunks** [syncfusion/blazor-showcase-diagram-builder#16]
When I try build the MAUI Diagrams demo - build errors

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'NodeFlowShapes' does not exist in the current context	DiagramBuilderMAUI (net6.0-android), DiagramBuilderMAUI (net6.0-ios), DiagramBuilderMAUI (net6.0-maccatalyst), DiagramBuilderMAUI (net6.0-windows10.0.19041.0)	
blazor-showcase-diagram-builder-master\blazor-showcase-diagram-builder-master\MAUI\DiagramBuilderMAUI\Pages\DiagramMainContent.cs	106	Active

**Comment by SumathiSumi** [comment]
The reported problem has been verified. We suspect you ran the MAUI sample with Nuget (Syncfusion.Blazor) version 20.1.0.55, which is why you encountered the error (Error CS0103: The name "NodeFlowShapes" does not exist in the current context of DiagramBuilderMAUI) that is mentioned in your query. To resolve the reported issue, please update your application's "Syncfusion.Blazor" package to the latest version for all platforms that are mentioned in your query (DiagramBuilderMAUI (net6.0-android), DiagramBuilderMAUI (net6.0-ios), DiagramBuilderMAUI (net6.0-maccatalyst), and DiagramBuilderMAUI (net6.0-windows10.0.19041.0)). Below, we have shared the package link. We have also resolved this issue on our end. Please update your branch (blazor-showcase-diagram-builder-master)

https://www.nuget.org/packages/Syncfusion.Blazor
