### ISSUE TITLE
Maui example: add image button does not work

### ISSUE THREAD

**Issue by BlockchainPunks** [syncfusion/blazor-showcase-diagram-builder#25]
The maui example add image button doesn’t work - when clicked nothing happens.

min the server example a dialog pops up to allow selection of image to add, then when added image shows on diagram.

**Comment by Keerthivasan-Ramamoorthy** [comment]
We were able to replicate the reported issue. This issue occurs because the script is not properly referred to in the application, and we have resolved it by adding the following line to the index.html file. Please update your local [blazor-showcase-diagram-builder](https://github.com/syncfusion/blazor-showcase-diagram-builder) repository.

https://github.com/syncfusion/blazor-showcase-diagram-builder/pull/24
